<#
.SYNOPSIS
    FreeNameConvention – Standalone Folder Protection Script
    Template for exported protection scripts

.DESCRIPTION
    This script validates file naming compliance in a specified folder.
    It can run in two modes:
    - Scan: Checks all existing files against defined patterns
    - Monitor: Watches for new files and enforces naming conventions in real-time

    Generated by FreeNameConvention Guardian
    https://github.com/freenameconvention/guardian

.PARAMETER FolderPath
    The folder path to protect

.PARAMETER Mode
    Operation mode: 'scan' or 'monitor'

.PARAMETER Action
    Enforcement action: 'log', 'quarantine', or 'block'

.PARAMETER QuarantineFolder
    Name of the subfolder for non-compliant files (default: _NONCOMPLIANT)

.PARAMETER Patterns
    Array of naming patterns using FreeNameConvention tokens

.EXAMPLE
    .\protect-folder.ps1 -FolderPath "C:\Documents" -Mode scan -Patterns @("{TEXT}-{NUM:5}-{DATE}")

.EXAMPLE
    .\protect-folder.ps1 -FolderPath "C:\Documents" -Mode monitor -Action block

.NOTES
    License: MIT | Free and Open Source
    Mission: Help every company and person achieve the maximum in file organization.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$FolderPath,

    [Parameter(Mandatory=$true)]
    [ValidateSet('scan', 'monitor')]
    [string]$Mode,

    [ValidateSet('log', 'quarantine', 'block')]
    [string]$Action = 'log',

    [string]$QuarantineFolder = '_NONCOMPLIANT',

    [string[]]$Patterns = @()
)

# ═══════════════════════════════════════════════════════════════════════════
# Pattern Engine
# ═══════════════════════════════════════════════════════════════════════════

function Convert-PatternToRegex {
    param([string]$Pattern)

    $regex = [regex]::Escape($Pattern)

    $regex = $regex -replace '\\\{(TEXT|TEXTO)\\\}', '[A-Za-z0-9_]+'
    $regex = $regex -replace '\\\{NUM:(\d+)\\\}', { '\d{' + $_.Groups[1].Value + '}' }
    $regex = $regex -replace '\\\{(DATE|DATA):YYYY-MM\\\}', '\d{4}-\d{2}'
    $regex = $regex -replace '\\\{(DATE|DATA):YYYY\\\}', '\d{4}'
    $regex = $regex -replace '\\\{(DATE|DATA)\\\}', '\d{4}-\d{2}-\d{2}'
    $regex = $regex -replace '\\\{(VERSION|VERSAO)\\\}', 'v?\d+(\.\d+)*'
    $regex = $regex -replace '\\\{HASH:(\d+)\\\}', { '[0-9a-fA-F]{' + $_.Groups[1].Value + '}' }
    $regex = $regex -replace '\\\{UUID\\\}', '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
    $regex = $regex -replace '\\\{ANY\\\}', '.+'

    return "^$regex$"
}

function Test-FileCompliance {
    param(
        [string]$FileName,
        [string[]]$PatternList
    )

    $nameOnly = [System.IO.Path]::GetFileNameWithoutExtension($FileName)

    foreach ($pattern in $PatternList) {
        $regex = Convert-PatternToRegex -Pattern $pattern
        if ($nameOnly -match $regex) {
            return $true
        }
    }

    return $false
}

# ═══════════════════════════════════════════════════════════════════════════
# Quarantine / Block
# ═══════════════════════════════════════════════════════════════════════════

function Move-ToQuarantine {
    param(
        [string]$FilePath,
        [string]$QuarantineDir
    )

    if (-not (Test-Path $QuarantineDir)) {
        New-Item -Path $QuarantineDir -ItemType Directory -Force | Out-Null
    }

    $fileName = [System.IO.Path]::GetFileName($FilePath)
    $dest = Join-Path $QuarantineDir $fileName

    # Avoid overwriting — append timestamp if exists
    if (Test-Path $dest) {
        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
        $ext = [System.IO.Path]::GetExtension($fileName)
        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $dest = Join-Path $QuarantineDir "${baseName}_${timestamp}${ext}"
    }

    try {
        Move-Item -Path $FilePath -Destination $dest -Force
        Write-Host "[QUARANTINE] $fileName -> $dest" -ForegroundColor Yellow
    }
    catch {
        Write-Host "[ERROR] Failed to move $fileName : $_" -ForegroundColor Red
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# Scan Mode
# ═══════════════════════════════════════════════════════════════════════════

function Start-Scan {
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  FreeNameConvention – Folder Scan" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Folder:  $FolderPath" -ForegroundColor White
    Write-Host "  Action:  $Action" -ForegroundColor White
    Write-Host "  Patterns: $($Patterns.Count)" -ForegroundColor White
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""

    if ($Patterns.Count -eq 0) {
        Write-Host "[WARNING] No patterns defined. Nothing to validate." -ForegroundColor Yellow
        return
    }

    $quarantineDir = Join-Path $FolderPath $QuarantineFolder
    $files = Get-ChildItem -Path $FolderPath -File -Recurse |
             Where-Object { $_.DirectoryName -notlike "*\$QuarantineFolder*" }

    $total = 0
    $compliant = 0
    $violations = 0

    foreach ($file in $files) {
        $total++
        $isCompliant = Test-FileCompliance -FileName $file.Name -PatternList $Patterns

        if ($isCompliant) {
            $compliant++
            Write-Host "[OK] $($file.Name)" -ForegroundColor Green
        }
        else {
            $violations++
            Write-Host "[VIOLATION] $($file.Name)" -ForegroundColor Red

            if ($Action -eq 'quarantine' -or $Action -eq 'block') {
                Move-ToQuarantine -FilePath $file.FullName -QuarantineDir $quarantineDir
            }
        }
    }

    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Scan Complete" -ForegroundColor Cyan
    Write-Host "  Total: $total | Compliant: $compliant | Violations: $violations" -ForegroundColor White
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
}

# ═══════════════════════════════════════════════════════════════════════════
# Monitor Mode (Real-time using FileSystemWatcher)
# ═══════════════════════════════════════════════════════════════════════════

function Start-Monitor {
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  FreeNameConvention – Real-time Monitor" -ForegroundColor Cyan
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  Folder:  $FolderPath" -ForegroundColor White
    Write-Host "  Action:  $Action" -ForegroundColor White
    Write-Host "  Patterns: $($Patterns.Count)" -ForegroundColor White
    Write-Host "  Press Ctrl+C to stop" -ForegroundColor Yellow
    Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""

    if ($Patterns.Count -eq 0) {
        Write-Host "[WARNING] No patterns defined. Nothing to validate." -ForegroundColor Yellow
        return
    }

    $quarantineDir = Join-Path $FolderPath $QuarantineFolder

    $watcher = New-Object System.IO.FileSystemWatcher
    $watcher.Path = $FolderPath
    $watcher.IncludeSubdirectories = $true
    $watcher.EnableRaisingEvents = $true

    $actionBlock = {
        $name = $Event.SourceEventArgs.Name
        $path = $Event.SourceEventArgs.FullPath
        $changeType = $Event.SourceEventArgs.ChangeType

        # Skip quarantine folder
        if ($path -like "*\$($QuarantineFolder)*") { return }

        # Only validate files (not directories)
        if (-not (Test-Path $path -PathType Leaf)) { return }

        $fileName = [System.IO.Path]::GetFileName($path)
        $isCompliant = $false

        foreach ($pattern in $Patterns) {
            $nameOnly = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
            $regex = "^" + [regex]::Escape($pattern) + "$"
            $regex = $regex -replace '\\\{(TEXT|TEXTO)\\\}', '[A-Za-z0-9_]+'
            $regex = $regex -replace '\\\{NUM:(\d+)\\\}', { '\d{' + $_.Groups[1].Value + '}' }
            $regex = $regex -replace '\\\{(DATE|DATA):YYYY-MM\\\}', '\d{4}-\d{2}'
            $regex = $regex -replace '\\\{(DATE|DATA):YYYY\\\}', '\d{4}'
            $regex = $regex -replace '\\\{(DATE|DATA)\\\}', '\d{4}-\d{2}-\d{2}'
            $regex = $regex -replace '\\\{(VERSION|VERSAO)\\\}', 'v?\d+(\.\d+)*'
            $regex = $regex -replace '\\\{HASH:(\d+)\\\}', { '[0-9a-fA-F]{' + $_.Groups[1].Value + '}' }
            $regex = $regex -replace '\\\{UUID\\\}', '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'
            $regex = $regex -replace '\\\{ANY\\\}', '.+'

            if ($nameOnly -match $regex) {
                $isCompliant = $true
                break
            }
        }

        $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

        if ($isCompliant) {
            Write-Host "[$timestamp] [OK] $fileName" -ForegroundColor Green
        }
        else {
            Write-Host "[$timestamp] [VIOLATION] $fileName ($changeType)" -ForegroundColor Red

            if ($Action -eq 'quarantine' -or $Action -eq 'block') {
                Start-Sleep -Milliseconds 500  # Wait for file write to complete
                if (Test-Path $path) {
                    if (-not (Test-Path $quarantineDir)) {
                        New-Item -Path $quarantineDir -ItemType Directory -Force | Out-Null
                    }
                    $dest = Join-Path $quarantineDir $fileName
                    if (Test-Path $dest) {
                        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($fileName)
                        $ext = [System.IO.Path]::GetExtension($fileName)
                        $ts = Get-Date -Format "yyyyMMdd_HHmmss"
                        $dest = Join-Path $quarantineDir "${baseName}_${ts}${ext}"
                    }
                    try {
                        Move-Item -Path $path -Destination $dest -Force
                        Write-Host "[$timestamp] [MOVED] $fileName -> $dest" -ForegroundColor Yellow
                    }
                    catch {
                        Write-Host "[$timestamp] [ERROR] Failed to move: $_" -ForegroundColor Red
                    }
                }
            }
        }
    }

    Register-ObjectEvent $watcher "Created" -Action $actionBlock | Out-Null
    Register-ObjectEvent $watcher "Renamed" -Action $actionBlock | Out-Null

    Write-Host "[MONITOR] Watching $FolderPath ..." -ForegroundColor Green

    try {
        while ($true) { Start-Sleep -Seconds 1 }
    }
    finally {
        $watcher.EnableRaisingEvents = $false
        $watcher.Dispose()
        Get-EventSubscriber | Unregister-Event
        Write-Host "`n[MONITOR] Stopped." -ForegroundColor Yellow
    }
}

# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════

if (-not (Test-Path $FolderPath)) {
    Write-Host "[ERROR] Folder not found: $FolderPath" -ForegroundColor Red
    exit 1
}

switch ($Mode) {
    'scan'    { Start-Scan }
    'monitor' { Start-Monitor }
}
